# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='response_data',
        ),
        migrations.RemoveField(
            model_name='api',
            name='test_result',
        ),
        migrations.AddField(
            model_name='api',
            name='expect_response_data',
            field=models.TextField(default=None, verbose_name='\u671f\u671b\u7ed3\u679c'),
        ),
        migrations.AddField(
            model_name='api',
            name='project_id',
            field=models.CharField(default=1, max_length=20, verbose_name='\u9879\u76eeID'),
        ),
        migrations.AlterField(
            model_name='api',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '\u7b49\u5f85'), (1, '\u7b49\u5f85'), (2, '\u6267\u884c\u4e2d'), (3, '\u5df2\u6267\u884c')], default=0, verbose_name='\u63a5\u53e3\u72b6\u6001'),
        ),
    ]
