# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='status',
        ),
    ]
