# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0002_remove_api_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='project_name',
        ),
    ]
